// Instalar a extensão "Rest Client" do VSCode

// Configurar o arquivo settings.json do VSCode :
// "rest-client.excludeHostsForProxy": ["localhost","127.0.0.1"]

@urlBase = http://localhost:3000

####################################################
## Login
####################################################

# @name login
POST {{urlBase}}/auth/login
Content-Type: application/json

{
  "email": "ibm@gmail.com",
  "password": "123456"
}

###
@access_token = {{login.response.body.$.access_token}}

################################
# USERS
################################

# @name getAllUsers
GET {{urlBase}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name addUser
POST {{urlBase}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "IBM",
    "email": "ibm@gmail.com",
    "password": "123456",
    "phone": "21981075493"
}

###
@id = {{addUser.response.body.$.id}}

###

# @name getCustomerById
GET {{urlBase}}/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name updateUser
PUT {{urlBase}}/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "name": "IBM (alt)",
    "email": "ibm@gmail.com",
    "password": "123456",
    "phone": "21981075493"
}

###

# @name deleteCustomer
DELETE {{urlBase}}/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

###